/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.rik.ase;

import java.awt.Font;
import java.net.URL;
import java.net.URLEncoder;
import org.json.JSONObject;
import org.openide.awt.HtmlBrowser.URLDisplayer;

/**
 *
 * @author Rik
 */
public class NewJPanel extends javax.swing.JPanel {
    
    private Location location;
    private Weather weather;
    

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {       
        setLocation(); 
        setWeather();
        initComponents();
        setLabels();
    }
    
    private void setWeather() {
        JSONObject json = Controller.getWeather(location.getCountryCode(), location.getCity());
        double degrees = (json.getJSONObject("main").getDouble("temp")) - 273.15;
        
        weather = new Weather(degrees);
    }
    
    private void setLocation() {
        JSONObject json = Controller.getLocation();
        String countryCode = json.getString("countryCode");
        String city = json.getString("city");
        
        location = new Location(countryCode, city);
    }
    
    private void setLabels() {
        Font labelFont = (new Font("Helvetica", Font.PLAIN, 16));
        
        jLabel1.setFont(labelFont);
        jLabel2.setFont(labelFont);
        jLabel1.setText(location.getCity()+":");
        jLabel2.setText((double)Math.round(weather.getDegrees() * 10d) / 10d+" graden celcius");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NewJPanel.class, "NewJPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(NewJPanel.class, "NewJPanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
